name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run tests
      run: cargo test

  test-windows:

    runs-on: windows-2019

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run tests
      run: cargo test

  test-macos:

    runs-on: macos-11

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run tests
      run: cargo test
